
version: '3.8'
services:
  cert_exporter:
    build: .
    environment:
      - ACME_JSON_PATH=/acme.json
      - CERTS_DIR=/certs
      - DOMAINS=example.com,anotherdomain.com
      - DEBUG=true
      - LOG_FILE=/var/log/extract_certs.log
    volumes:
      - ./acme.json:/acme.json
      - ./certs:/certs
      - ./logs:/var/log
    stop_grace_period: 5s
